name: Generate Snake Animation

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ayieeez
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00ff41&color_dots=#0d1117,#1a0033,#39ff14,#00ffff,#ff00ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}